### ISSUE TITLE
Stream playback very slow

### ISSUE THREAD

**Issue by ferenczAndras** [vbartacek/aacdecoder-android#79]
Hello. I am using this library for a local radio, and i saw that few times when i start the radio, the playback is very very slow. If i stop the radio and restart it, than works ok. What can be the problem ?

**Comment by ruben2315** [comment]
I'm having the same problem here.
Using https://github.com/AlexisCaffa/cordova-plugin-mediaac and Icecast audio sources, sometimes (very few, 1/10), playback starts very slow, other few times starts faster than normal. 

It happens all the same with all connection types ( Wifi, 3G, 4G.. ) 

If I stop and start it works fine most of the times. 

¿Any solution or clue for this issue?
