### ISSUE TITLE
UnsatisfiedLinkError 64 processors

### ISSUE THREAD

**Issue by A7med7ani** [vbartacek/aacdecoder-android#99]
lib/arm64-v8a, /system/lib64]]] couldn't find "libaacdecoder.so"

**Comment by andrescheca** [comment]
Here is the zip file with the compiled libaacdecoder files for 64 bits
[aacdecoder.zip](https://github.com/vbartacek/aacdecoder-android/files/3585512/aacdecoder.zip)

**Comment by A7med7ani** [comment]
@andrescheca  Thank you very much 👍 💯
